### PR TITLE
Fix problem with checking nested constraint condition when nested target is null

### LINKED ISSUE #145: nestIfPresent with conditional constraint throws exception when target is null
Hi @making 

I'm not sure it is a bug but when I use nestIfPresent with conditional constraint and target is null then I get an exception (NullPointerException). 

For example, I have the following test:

```java
 public class OptionalNestedConstraintWithConditionConstraintTest {
    @Test
    void shouldBeValidAddressWithoutCountry() {
        Validator<Address> addressValidator = ValidatorBuilder.of(Address.class)
                .constraint(Address::getCity, "city", city -> city.notBlank())
                .nestIfPresent(Address::getCountry, "country", countryValidatorBuilder -> countryValidatorBuilder
                        .constraint(Country::getCode, "code", code -> code.lessThan(3))
                        .constraintOnCondition((country, group) -> country.getName() != null, conditionalCountryBuilder -> conditionalCountryBuilder
                                .constraint(Country::getCode, "code", code -> code.notBlank())))
                .build();
        Address address = new Address("Paris", null);

        ConstraintViolations violations = addressValidator.validate(address);

        assertThat(violations.isValid()).isTrue();
    }

    @Test
    void shouldBeValidPersonWithoutAddress() {
        Validator<Person> personValidator = ValidatorBuilder.of(Person.class)
                .constraint(Person::getName, "name", name -> name.notBlank())
                .nestIfPresent(Person::getAddress, "address", addressValidatorBuilder -> addressValidatorBuilder
                        .constraint(Address::getCity, "city", city -> city.notBlank())
                        .nestIfPresent(Address::getCountry, "country", countryValidatorBuilder -> countryValidatorBuilder
                                .constraint(Country::getCode, "code", code -> code.lessThan(3))
                                .constraintOnCondition((country, group) -> country.getName() != null, conditionalCountryBuilder -> conditionalCountryBuilder
                                        .constraint(Country::getCode, "code", code -> code.notBlank()))
                        ))
                .build();
        Person person = new Person("Jack", null);

        ConstraintViolations violations = personValidator.validate(person);

        assertThat(violations.isValid()).isTrue();
    }

    private static class Person {
        private String name;
        private Address address;

        public Person(String name, Address address) {
            this.name = name;
            this.address = address;
        }

        public String getName() {
            return name;
        }

        public Address getAddress() {
            return address;
        }
    }

    private static class Address {
        private String city;
        private Country country;

        public Address(String city, Country country) {
            this.city = city;
            this.country = country;
        }

        public String getCity() {
            return city;
        }

        public Country getCountry() {
            return country;
        }
    }

    private static class Country {
        private String code;
        private String name;

        public Country(String code, String name) {
            this.code = code;
            this.name = name;
        }

        public String getCode() {
            return code;
        }

        public String getName() {
            return name;
        }
    }
}
```
I get the following exceptions:
a) 
```
java.lang.NullPointerException
	at am.ik.yavi.core.OptionalNestedConstraintWithConditionConstraintTest.lambda$null$2(OptionalNestedConstraintWithConditionConstraintTest.java:15)
	at am.ik.yavi.core.NestedConstraintCondition.test(NestedConstraintCondition.java:34)
	at am.ik.yavi.core.NestedConstraintCondition.test(NestedConstraintCondition.java:20)
	at am.ik.yavi.core.Validator.lambda$validate$3(Validator.java:328)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at am.ik.yavi.core.Validator.validate(Validator.java:326)
	at am.ik.yavi.core.Validator.validate(Validator.java:152)
	at am.ik.yavi.core.Validator.validate(Validator.java:165)
	at am.ik.yavi.core.OptionalNestedConstraintWithConditionConstraintTest.shouldBeValidAddressWithoutCountry(OptionalNestedConstraintWithConditionConstraintTest.java:20)
```
b)
```
java.lang.NullPointerException
	at am.ik.yavi.core.NestedConstraintCondition.test(NestedConstraintCondition.java:33)
	at am.ik.yavi.core.NestedConstraintCondition.test(NestedConstraintCondition.java:20)
	at am.ik.yavi.core.NestedConstraintCondition.test(NestedConstraintCondition.java:34)
	at am.ik.yavi.core.NestedConstraintCondition.test(NestedConstraintCondition.java:20)
	at am.ik.yavi.core.Validator.lambda$validate$3(Validator.java:328)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at am.ik.yavi.core.Validator.validate(Validator.java:326)
	at am.ik.yavi.core.Validator.validate(Validator.java:152)
	at am.ik.yavi.core.Validator.validate(Validator.java:165)
	at am.ik.yavi.core.OptionalNestedConstraintWithConditionConstraintTest.shouldBeValidPersonWithoutAddress(OptionalNestedConstraintWithConditionConstraintTest.java:39)
```

In this case I expect that conditional constraints are not evaluated so I do not have to check nullable in the predicate. Maybe I'm wrong. I would be appreciate for clarification. 

I checked this in 0.6.1 and 0.7.0 and the results are the same.

### PR DESCRIPTION
**Pull request by ddzida**
fixes #145

### CODE REVIEW

**Comment by making** [comment]
@ddzida Thank you for testing the complex case as usual. Your contribution enhances YAVI.

File: src/main/java/am/ik/yavi/core/NestedConstraintCondition.java [hunk 1]
```diff
@@ -31,6 +31,10 @@ public NestedConstraintCondition(Function<T, N> nested,
 	@Override
 	public boolean test(T t, ConstraintGroup constraintGroup) {
 		final N n = this.nested.apply(t);
+		if (n == null) {
+			return false;
```
Comment (making) [inline src/main/java/am/ik/yavi/core/NestedConstraintCondition.java:35]: Let me think carefully about whether the value changes when using `nest` and when using `nestIfPresent`.

Comment (making) [reply src/main/java/am/ik/yavi/core/NestedConstraintCondition.java:35]: Seems OK
